version: '3.8'

services:
  # Carla server container
  carla_server:
    image: carlasim/carla:0.9.15
    container_name: carla_server
    command: ["/bin/bash", "./CarlaUE4.sh", "-nosound", "-vulkan", "-RenderOffScreen"]
    runtime: nvidia
    privileged: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    healthcheck:
      test: ["CMD", "sleep", "5"]
      interval: 5s
      timeout: 10s
      retries: 5

  carla_steering_example:
    build:
      context: ./docker/carla_steering_example/
      dockerfile: Dockerfile
    image: carla_steering_example:latest
    container_name: carla_steering_example
    runtime: nvidia
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - SDL_VIDEODRIVER=x11
      - SDL_AUDIODRIVER=waveout
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: python3 manual_control_steeringwheel.py --host carla_server --port 2000
    depends_on:
      carla_server:
        condition: service_healthy

